export const KeyCodes = {
    BACKSPACE: 8,
    TAB: 9,
    ENTER: 13,
    SHIFT: 16,
    CTRL: 17,
    ALT: 18,
    PAUSE: 19,
    CAPS_LOCK: 20,
    ESC: 27,
    SPACE: 32,
    PAGE_UP: 33,
    PAGE_DOWN: 34,
    END: 35,
    HOME: 36,
    LEFT: 37,
    UP: 38,
    RIGHT: 39,
    DOWN: 40,
    PRINT_SCREEN: 42,
    INSERT: 45,
    DELETE: 46,
    ZERO: 48,
    ONE: 49,
    TWO: 50,
    THREE: 51,
    FOUR: 52,
    FIVE: 53,
    SIX: 54,
    SEVEN: 55,
    EIGHT: 56,
    NINE: 57,
    NUMPAD_ZERO: 96,
    NUMPAD_ONE: 97,
    NUMPAD_TWO: 98,
    NUMPAD_THREE: 99,
    NUMPAD_FOUR: 100,
    NUMPAD_FIVE: 101,
    NUMPAD_SIX: 102,
    NUMPAD_SEVEN: 103,
    NUMPAD_EIGHT: 104,
    NUMPAD_NINE: 105,
    NUMPAD_ADD: 107,
    NUMPAD_SUBTRACT: 109,
    A: 65,
    B: 66,
    C: 67,
    D: 68,
    E: 69,
    F: 70,
    G: 71,
    H: 72,
    I: 73,
    J: 74,
    K: 75,
    L: 76,
    M: 77,
    N: 78,
    O: 79,
    P: 80,
    Q: 81,
    R: 82,
    S: 83,
    T: 84,
    U: 85,
    V: 86,
    W: 87,
    X: 88,
    Y: 89,
    Z: 90,
    F1: 112,
    F2: 113,
    F3: 114,
    F4: 115,
    F5: 116,
    F6: 117,
    F7: 118,
    F8: 119,
    F9: 120,
    F10: 121,
    F11: 122,
    F12: 123,
    SEMICOLON: 186,
    PLUS: 187,
    COMMA: 188,
    MINUS: 189,
    PERIOD: 190,
    FORWARD_SLASH: 191,
    BACK_SLASH: 220,
    QUOTES: 222,
    BACKTICK: 192,
    OPEN_BRACKET: 219,
    CLOSED_BRACKET: 221,
    SEMICOLON_FIREFOX: 59,
    COLON: 58,
    COMMA_FIREFOX_WINDOWS: 60,
    COMMA_FIREFOX: 62,
    BRACKET_RIGHT_FIREFOX: 174,
    BRACKET_LEFT_FIREFOX: 175
};

// todo: these will be configurable
export const GamepadCodes = {
    A: 0,
    B: 1,
    X: 2,
    Y: 3,
    LB: 4,
    RB: 5,
    LT: 6,
    RT: 7,
    SELECT: 8,
    START: 9,
    LS: 10,
    RS: 11,
    UP: 12,
    DOWN: 13,
    LEFT: 14,
    RIGHT: 15,
    HOME: 16,

    // the rest of these are like
    // axis mappings
    LS_UP: 100,
    LS_DOWN: 101,
    LS_LEFT: 102,
    LS_RIGHT: 103,
    RS_UP: 104,
    RS_DOWN: 105,
    RS_LEFT: 106,
    RS_RIGHT: 107,

    // 8bitdo micro buttons lol
    // A: 0,
    // B: 1,
    // X: 3,
    // Y: 4,
    // LB: 6,
    // RB: 7,
    // LT: 8,
    // RT: 9,
    // SELECT: 10,
    // START: 11,
    // LS: -1,
    // RS: -1,
    // UP: -1,
    // DOWN: -1,
    // LEFT: -1,
    // RIGHT: -1,
}

export const GamepadAxisCodes = {
    LSX: 0,
    LSY: 1,
    RSX: 2,
    RSY: 3,
}

export const DefaultGamepadAxisMapping = {
    [GamepadAxis.LSX]: {
        pos: GamepadCodes.LS_RIGHT,
        neg: GamepadCodes.LS_LEFT,
    },
    [GamepadAxis.LSY]: {
        pos: GamepadCodes.LS_DOWN,
        neg: GamepadCodes.LS_UP,
    },
    [GamepadAxis.RSX]: {
        pos: GamepadCodes.RS_RIGHT,
        neg: GamepadCodes.RS_LEFT,
    },
    [GamepadAxis.RSY]: {
        pos: GamepadCodes.RS_DOWN,
        neg: GamepadCodes.RS_UP,
    }, 
}

// todo: rename these to default
export const GamepadKeybinds = {
    'up': GamepadCodes.LS_UP,
    'down': GamepadCodes.LS_DOWN,
    'left': GamepadCodes.LS_LEFT,
    'right': GamepadCodes.LS_RIGHT,
    'leftTrigger': GamepadCodes.LT,
    'rightTrigger': GamepadCodes.RT,
    'leftBumper': GamepadCodes.LB,
    'rightBumper': GamepadCodes.RB,
    'start': GamepadCodes.START,
    'select': GamepadCodes.SELECT,
    'dpadUp': GamepadCodes.UP,
    'dpadDown': GamepadCodes.DOWN,
    'dpadLeft': GamepadCodes.LEFT,
    'dpadRight': GamepadCodes.RIGHT,
    'gamepadA': GamepadCodes.A,
    'gamepadB': GamepadCodes.B,
    'gamepadX': GamepadCodes.X,
    'gamepadY': GamepadCodes.Y,
}


export const DefaultKeybinds = {
  'confirm': KeyCodes.ENTER,
  'cancel': KeyCodes.ESC,
  'up': KeyCodes.UP,
  'down': KeyCodes.DOWN,
  'left': KeyCodes.LEFT,
  'right': KeyCodes.RIGHT,
  'cycleR': KeyCodes.TAB,
  'cycleL': [KeyCodes.SHIFT, KeyCodes.TAB],
}
