export const KeyCodes = {
    BACKSPACE: 8,
    TAB: 9,
    ENTER: 13,
    SHIFT: 16,
    CTRL: 17,
    ALT: 18,
    PAUSE: 19,
    CAPS_LOCK: 20,
    ESC: 27,
    SPACE: 32,
    PAGE_UP: 33,
    PAGE_DOWN: 34,
    END: 35,
    HOME: 36,
    LEFT: 37,
    UP: 38,
    RIGHT: 39,
    DOWN: 40,
    PRINT_SCREEN: 42,
    INSERT: 45,
    DELETE: 46,
    ZERO: 48,
    ONE: 49,
    TWO: 50,
    THREE: 51,
    FOUR: 52,
    FIVE: 53,
    SIX: 54,
    SEVEN: 55,
    EIGHT: 56,
    NINE: 57,
    NUMPAD_ZERO: 96,
    NUMPAD_ONE: 97,
    NUMPAD_TWO: 98,
    NUMPAD_THREE: 99,
    NUMPAD_FOUR: 100,
    NUMPAD_FIVE: 101,
    NUMPAD_SIX: 102,
    NUMPAD_SEVEN: 103,
    NUMPAD_EIGHT: 104,
    NUMPAD_NINE: 105,
    NUMPAD_ADD: 107,
    NUMPAD_SUBTRACT: 109,
    A: 65,
    B: 66,
    C: 67,
    D: 68,
    E: 69,
    F: 70,
    G: 71,
    H: 72,
    I: 73,
    J: 74,
    K: 75,
    L: 76,
    M: 77,
    N: 78,
    O: 79,
    P: 80,
    Q: 81,
    R: 82,
    S: 83,
    T: 84,
    U: 85,
    V: 86,
    W: 87,
    X: 88,
    Y: 89,
    Z: 90,
    F1: 112,
    F2: 113,
    F3: 114,
    F4: 115,
    F5: 116,
    F6: 117,
    F7: 118,
    F8: 119,
    F9: 120,
    F10: 121,
    F11: 122,
    F12: 123,
    SEMICOLON: 186,
    PLUS: 187,
    COMMA: 188,
    MINUS: 189,
    PERIOD: 190,
    FORWARD_SLASH: 191,
    BACK_SLASH: 220,
    QUOTES: 222,
    BACKTICK: 192,
    OPEN_BRACKET: 219,
    CLOSED_BRACKET: 221,
    SEMICOLON_FIREFOX: 59,
    COLON: 58,
    COMMA_FIREFOX_WINDOWS: 60,
    COMMA_FIREFOX: 62,
    BRACKET_RIGHT_FIREFOX: 174,
    BRACKET_LEFT_FIREFOX: 175
};

export const KeyCodeLabels = {
    [KeyCodes.BACKSPACE]: "Bksp",
    [KeyCodes.TAB]: "Tab",
    [KeyCodes.ENTER]: "Enter",
    [KeyCodes.SHIFT]: "⇧", // Shift
    [KeyCodes.CTRL]: "^", // Ctrl
    [KeyCodes.ALT]: "⎇", // Alt
    [KeyCodes.PAUSE]: "Pause",
    [KeyCodes.CAPS_LOCK]: "CpsLk",
    [KeyCodes.ESC]: "Esc",
    [KeyCodes.SPACE]: "Space",
    [KeyCodes.PAGE_UP]: "PgUp",
    [KeyCodes.PAGE_DOWN]: "PgDown",
    [KeyCodes.END]: "End",
    [KeyCodes.HOME]: "Home",
    [KeyCodes.LEFT]: "Left",
    [KeyCodes.UP]: "Up",
    [KeyCodes.RIGHT]: "Right",
    [KeyCodes.DOWN]: "Down",
    [KeyCodes.PRINT_SCREEN]: "PrtScn",
    [KeyCodes.INSERT]: "Ins",
    [KeyCodes.DELETE]: "Del",
    [KeyCodes.ZERO]: "0",
    [KeyCodes.ONE]: "1",
    [KeyCodes.TWO]: "2",
    [KeyCodes.THREE]: "3",
    [KeyCodes.FOUR]: "4",
    [KeyCodes.FIVE]: "5",
    [KeyCodes.SIX]: "6",
    [KeyCodes.SEVEN]: "7",
    [KeyCodes.EIGHT]: "8",
    [KeyCodes.NINE]: "9",
    [KeyCodes.NUMPAD_ZERO]: "Num0",
    [KeyCodes.NUMPAD_ONE]: "Num1",
    [KeyCodes.NUMPAD_TWO]: "Num2",
    [KeyCodes.NUMPAD_THREE]: "Num3",
    [KeyCodes.NUMPAD_FOUR]: "Num4",
    [KeyCodes.NUMPAD_FIVE]: "Num5",
    [KeyCodes.NUMPAD_SIX]: "Num6",
    [KeyCodes.NUMPAD_SEVEN]: "Num7",
    [KeyCodes.NUMPAD_EIGHT]: "Num8",
    [KeyCodes.NUMPAD_NINE]: "Num9",
    [KeyCodes.NUMPAD_ADD]: "Num+",
    [KeyCodes.NUMPAD_SUBTRACT]: "Num-",
    [KeyCodes.A]: "A",
    [KeyCodes.B]: "B",
    [KeyCodes.C]: "C",
    [KeyCodes.D]: "D",
    [KeyCodes.E]: "E",
    [KeyCodes.F]: "F",
    [KeyCodes.G]: "G",
    [KeyCodes.H]: "H",
    [KeyCodes.I]: "I",
    [KeyCodes.J]: "J",
    [KeyCodes.K]: "K",
    [KeyCodes.L]: "L",
    [KeyCodes.M]: "M",
    [KeyCodes.N]: "N",
    [KeyCodes.O]: "O",
    [KeyCodes.P]: "P",
    [KeyCodes.Q]: "Q",
    [KeyCodes.R]: "R",
    [KeyCodes.S]: "S",
    [KeyCodes.T]: "T",
    [KeyCodes.U]: "U",
    [KeyCodes.V]: "V",
    [KeyCodes.W]: "W",
    [KeyCodes.X]: "X",
    [KeyCodes.Y]: "Y",
    [KeyCodes.Z]: "Z",
    [KeyCodes.F1]: "F1",
    [KeyCodes.F2]: "F2",
    [KeyCodes.F3]: "F3",
    [KeyCodes.F4]: "F4",
    [KeyCodes.F5]: "F5",
    [KeyCodes.F6]: "F6",
    [KeyCodes.F7]: "F7",
    [KeyCodes.F8]: "F8",
    [KeyCodes.F9]: "F9",
    [KeyCodes.F10]: "F10",
    [KeyCodes.F11]: "F11",
    [KeyCodes.F12]: "F12",
    [KeyCodes.SEMICOLON]: ";",
    [KeyCodes.PLUS]: "+",
    [KeyCodes.COMMA]: ",",
    [KeyCodes.MINUS]: "-",
    [KeyCodes.PERIOD]: ".",
    [KeyCodes.FORWARD_SLASH]: "/",
    [KeyCodes.BACK_SLASH]: "\\",
    [KeyCodes.QUOTES]: "'",
    [KeyCodes.BACKTICK]: "`",
    [KeyCodes.OPEN_BRACKET]: "[",
    [KeyCodes.CLOSED_BRACKET]: "]",
    [KeyCodes.SEMICOLON_FIREFOX]: ";",
    [KeyCodes.COLON]: ":",
    [KeyCodes.COMMA_FIREFOX_WINDOWS]: ",",
    [KeyCodes.COMMA_FIREFOX]: ",",
    [KeyCodes.BRACKET_RIGHT_FIREFOX]: "]",
    [KeyCodes.BRACKET_LEFT_FIREFOX]: "["
}

export const GamepadCodes = {
    A: 0,
    B: 1,
    X: 2,
    Y: 3,
    LB: 4,
    RB: 5,
    LT: 6,
    RT: 7,
    SELECT: 8,
    START: 9,
    LS: 10,
    RS: 11,
    UP: 12,
    DOWN: 13,
    LEFT: 14,
    RIGHT: 15,
    LS_UP: 100,
    LS_DOWN: 101,
    LS_LEFT: 102,
    LS_RIGHT: 103,
    RS_UP: 104,
    RS_DOWN: 105,
    RS_LEFT: 106,
    RS_RIGHT: 107,

    // 8bitdo micro buttons lol
    // A: 0,
    // B: 1,
    // X: 3,
    // Y: 4,
    // LB: 6,
    // RB: 7,
    // LT: 8,
    // RT: 9,
    // SELECT: 10,
    // START: 11,
    // LS: -1,
    // RS: -1,
    // UP: -1,
    // DOWN: -1,
    // LEFT: -1,
    // RIGHT: -1,
}


export const GamepadKeybinds = {
    'up': GamepadCodes.LS_UP,
    'down': GamepadCodes.LS_DOWN,
    'left': GamepadCodes.LS_LEFT,
    'right': GamepadCodes.LS_RIGHT,
    'leftTrigger': GamepadCodes.LT,
    'rightTrigger': GamepadCodes.RT,
    'leftBumper': GamepadCodes.LB,
    'rightBumper': GamepadCodes.RB,
    'start': GamepadCodes.START,
    'select': GamepadCodes.SELECT,
    'dpadUp': GamepadCodes.UP,
    'dpadDown': GamepadCodes.DOWN,
    'dpadLeft': GamepadCodes.LEFT,
    'dpadRight': GamepadCodes.RIGHT,
    'gamepadA': GamepadCodes.A,
    'gamepadB': GamepadCodes.B,
    'gamepadX': GamepadCodes.X,
    'gamepadY': GamepadCodes.Y,
}

// todo: eventually we want multiple schemas of this
// todo: also we're gonna replace these with <KeybindLabel>
// components and render based on name from prop
export const GamepadLabels = {
    [GamepadCodes.LS_UP]: 'LS_UP',
    [GamepadCodes.LS_DOWN]: 'LS_DOWN',
    [GamepadCodes.LS_LEFT]: 'LS_LEFT',
    [GamepadCodes.LS_RIGHT]: 'LS_RIGHT',
    [GamepadCodes.LT]: 'LT',
    [GamepadCodes.RT]: 'RT',
    [GamepadCodes.LB]: 'LB',
    [GamepadCodes.RB]: 'RB',
    [GamepadCodes.START]: 'Start',
    [GamepadCodes.SELECT]: 'Select',
    [GamepadCodes.UP]: 'Up',
    [GamepadCodes.DOWN]: 'Down',
    [GamepadCodes.LEFT]: 'Left',
    [GamepadCodes.RIGHT]: 'Right',
    [GamepadCodes.A]: 'A',
    [GamepadCodes.B]: 'B',
    [GamepadCodes.X]: 'X',
    [GamepadCodes.Y]: 'Y',
}
